// ================================
// characters.js — Character Roster
// ================================

const CHARACTERS = [
  {
    id: 'chronomancer',
    name: 'Chronomancer',
    title: 'Master of Time',
    color: '#00d4ff',
    emoji: '🧙',
    description: 'Freezes enemies in time.',
    stats: { hp: 100, speed: 420, jumpStrength: -620, attackDamage: 12, attackCooldownMax: 1.0, abilityCooldownMax: 10 },
    ability: 'timestop',
    abilityLabel: 'TIME STOP',
    abilityKey: 'Z',
    // P1: Z, P2: 0 handled in player
  },
  {
    id: 'dasher',
    name: 'Dasher',
    title: 'The Blur',
    color: '#ff4d4d',
    emoji: '⚡',
    description: 'Blazing dash that deals damage.',
    stats: { hp: 90, speed: 480, jumpStrength: -640, attackDamage: 10, attackCooldownMax: 0.8, abilityCooldownMax: 5 },
    ability: 'dash',
    abilityLabel: 'DASH STRIKE',
    abilityKey: '0',
  },
  {
    id: 'titan',
    name: 'Titan',
    title: 'The Unmovable',
    color: '#f5a623',
    emoji: '🪨',
    description: 'Heavy and hard-hitting. Shockwave ability.',
    stats: { hp: 150, speed: 280, jumpStrength: -500, attackDamage: 20, attackCooldownMax: 1.5, abilityCooldownMax: 8 },
    ability: 'shockwave',
    abilityLabel: 'SHOCKWAVE',
    abilityKey: 'Z/0',
  },
  {
    id: 'phantom',
    name: 'Phantom',
    title: 'The Unseen',
    color: '#b39ddb',
    emoji: '👻',
    description: 'Turns invisible for 2 seconds.',
    stats: { hp: 80, speed: 460, jumpStrength: -660, attackDamage: 14, attackCooldownMax: 0.9, abilityCooldownMax: 7 },
    ability: 'invisibility',
    abilityLabel: 'VANISH',
    abilityKey: 'Z/0',
  },
  {
    id: 'pyro',
    name: 'Pyro',
    title: 'The Inferno',
    color: '#ff6b35',
    emoji: '🔥',
    description: 'Burns enemies for damage over time.',
    stats: { hp: 95, speed: 400, jumpStrength: -610, attackDamage: 11, attackCooldownMax: 0.9, abilityCooldownMax: 6 },
    ability: 'burn',
    abilityLabel: 'IGNITE',
    abilityKey: 'Z/0',
  },
  {
    id: 'techno',
    name: 'Techno',
    title: 'The Engineer',
    color: '#00e676',
    emoji: '🤖',
    description: 'Deploys a temporary turret that auto-attacks.',
    stats: { hp: 100, speed: 390, jumpStrength: -600, attackDamage: 10, attackCooldownMax: 1.0, abilityCooldownMax: 12 },
    ability: 'turret',
    abilityLabel: 'DEPLOY TURRET',
    abilityKey: 'Z/0',
  },
];

// Story Mode NPC lineup — levels 1-10
const STORY_NPCS = [
  { charId: 'dasher',       name: 'The Rookie',    hpMult: 0.6, speedMult: 0.8,  damageMult: 0.6,  aiLevel: 1 },
  { charId: 'chronomancer', name: 'The Apprentice', hpMult: 0.8, speedMult: 0.9,  damageMult: 0.8,  aiLevel: 2 },
  { charId: 'pyro',         name: 'Ember',          hpMult: 0.9, speedMult: 1.0,  damageMult: 0.9,  aiLevel: 2 },
  { charId: 'phantom',      name: 'Shade',          hpMult: 1.0, speedMult: 1.1,  damageMult: 1.0,  aiLevel: 3 },
  { charId: 'titan',        name: 'Golem',          hpMult: 1.2, speedMult: 0.9,  damageMult: 1.1,  aiLevel: 3 },
  { charId: 'techno',       name: 'Unit-9',         hpMult: 1.1, speedMult: 1.0,  damageMult: 1.2,  aiLevel: 4 },
  { charId: 'dasher',       name: 'Blitz',          hpMult: 1.3, speedMult: 1.3,  damageMult: 1.1,  aiLevel: 4 },
  { charId: 'chronomancer', name: 'Time Thief',     hpMult: 1.4, speedMult: 1.1,  damageMult: 1.2,  aiLevel: 5 },
  { charId: 'phantom',      name: 'The Void',       hpMult: 1.5, speedMult: 1.2,  damageMult: 1.4,  aiLevel: 5 },
  { charId: 'titan',        name: '⚠ CHRONOLORD',   hpMult: 3.0, speedMult: 1.3,  damageMult: 2.0,  aiLevel: 6, isBoss: true },
];
